added profile main screen
BlackBullSquad/iOS-FakeNFT-StarterProject-Public pull request #61
Opened 2023-05-24 21:01 UTC by Filosuf

2023-05-26 17:04 UTC, AndreiChenchik requested changes
Как минимум конфликты пофиксить, ну и остальное как пожелания

2023-05-26 17:04 UTC, AndreiChenchik commented on FakeNFT/Scenes/Profile/Profile/ProfileTableViewCell.swift
> +        }
Как мне кажется это визуальное оверусложнение кода, если хочется сделать красиво можно написать экстеншн для view, который добавит `addSubviewForAutoLayout(_ view: UIView)`, который будет вызывать сначала view.tAMIC = false, а потом addSubview, чтобы потом сделать
```
self.addSubviewForAutoLayout(titleLabel)
self.addSubviewForAutoLayout(arrowImage)
```
И коротко и чисто будет, как идея

2023-05-26 17:04 UTC, AndreiChenchik commented on FakeNFT/Scenes/Profile/Profile/ProfileVC.swift
> +        nftApi.getProfile { [weak self] result in
Как идея: Я бы написал отдельную модель Profile чтобы использовать ее а не DTO, т.е. понадобится profileStore, который достает профили из бэкенда, перегоняет их в модель в нормальном формате, а дальше поставляет ее контроллеру, который сделает из нее ViewModel и уже нарисует все что надо. 

Что-то такое начал @maxim-papier собирать https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/blob/%2325-catalogue/FakeNFT/Services/Collections/CollectionStore.swift

2023-05-31 18:34 UTC, Filosuf commented on FakeNFT/Scenes/Profile/Profile/ProfileVC.swift
> +    private let nftApi: NftAPI = FakeNftAPI()
Не нашел нигде где бы FakeNftAPI() создавался централизованно. поэтому пока сделал так

2023-05-31 18:36 UTC, Filosuf commented on FakeNFT.xcodeproj/project.pbxproj
делал первый раз, надеюсь получилось нормально, но не понятно сколько этот PR провисит, возможно снова придётся править

2023-05-31 18:41 UTC, Filosuf commented on FakeNFT/Scenes/Profile/Profile/ProfileTableViewCell.swift
> +        }
по-моему норм выглядит. Пробегаем по массиву элементов отключаем translatesAutoresizingMaskIntoConstraints и добавляем на View. согласен, что твой вариант будет выглядеть проще в VC, но не уверен что в целом станет прозрачнее

2023-06-01 04:05 UTC, maxim-papier requested changes
Обрати внимание, что отступ от аватара пользователя до текста не такой как в макете Figma — должен быть 20 пунктов. 
<img width="475" alt="Screenshot 2023-06-01 at 10 02 05" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/109724501/04b8223a-24ad-45c4-8842-dd4512552827">

2023-06-01 04:10 UTC, maxim-papier commented
Иконки > что-то вытянуло по горизонтали. Вижу, что у тебя взят шеврон:

``` swift
imageView.image = UIImage(systemName: "chevron.right")
```

но выглядит он как `"greaterthan"` 🤷🏻‍♂️

<img width="298" alt="Screenshot 2023-06-01 at 10 05 44" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/109724501/3ba9176d-4fcd-4983-8d0d-4afc6b30a2c2">

2023-06-01 04:15 UTC, maxim-papier commented
+ ссылка на автора должна быть `.blue`, а сейчас чёрная

2023-06-10 13:06 UTC, maxim-papier approved these changes

2023-06-11 18:29 UTC, mmbabaev requested changes

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/MyNFT/MyNFTViewController.swift
> +        self.profile = profile
можно организовать так, чтобы текущий profile можно было получить из ProfileService

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/MyNFT/MyNFTViewController.swift
> +        switch descriptor {
хорошо сделано через SortDescriptor

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/MyNFT/MyNFTViewController.swift
> +        //
TODO? :)

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Profile/ProfileTableViewCell.swift
> +        }
мне кажется оба варианта норм

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Profile/ProfileVC.swift
> +//    private let urlTextButton: UITextView = {
лучше не оставлять закомментированный код в пр

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Profile/ProfileVC.swift
> +                return
снова нет обработки ошибок

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Profile/ProfileVC.swift
> +        switch indexPath.row {
тут можно подобно SortDescriptor вынести `enum ...: Int`, инициализировать его через indexPath.row и свитчиться по его кейсам

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Profile/ProfileVC.swift
> +            return
можно вставить assertionFailure

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Profile/ProfileVC.swift
> +        case 1: navigationController?.pushViewController(FavoritesNftViewController(profileService: profileService), animated: true)
Дополнительно можно добавить какой-то класс, который "собирает" модули экранов, чтобы не делать их в ViewController. 

Обычно такие классы называют Assembly, Builder, Module

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Scenes/Web/WebView.swift
> +        setupViews()
пропущен вызов super

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Services/ProfileService/NFT.swift
> +    init(id: String, createdAt: Date, name: String, description: String, price: Float, rating: Int, images: [URL]) {
<img width="291" alt="Screenshot 2023-06-11 at 21 23 09" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/12600807/87f6e837-54fa-4099-89f1-ea2b2cf22140">

чтобы добавить свой инит и при этом не писать дефолтный-автогенерируемый, можно использовать extension:

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Services/ProfileService/ProfilleService.swift
> +                DispatchQueue.main.async {
чтобы не писать много раз `DispatchQueue.main.async` всегда, можно создать отдельную переменную-кложуру наверху. Вы что-то делали подобное в проекте ImageList

`let completionOnMain = { result in DispatchQueueMain.async { completion(result) }`

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Services/ProfileService/ProfilleService.swift
> +                return
нет обработки ошибок

2023-06-11 18:29 UTC, mmbabaev commented on FakeNFT/Services/ProfileService/ProfilleService.swift
> +        let likesId = likes.compactMap { Int($0.id) }
likesId -> likeIds

2023-06-11 19:13 UTC, mmbabaev commented on FakeNFT.xcodeproj/project.pbxproj
[fix.patch](https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/files/11715477/fix.patch)
Похоже все-таки сломалось, долго провисел пр

2023-06-12 07:40 UTC, Filosuf commented on FakeNFT.xcodeproj/project.pbxproj
к сожалению не могу применить патч
No valid patches in input (allow with "--allow-empty")

2023-06-18 14:05 UTC, closed without merging