#25 catalogue
BlackBullSquad/iOS-FakeNFT-StarterProject-Public pull request #62
Opened 2023-05-31 12:08 UTC by maxim-papier

Task #25 Completion:

- Created `CollectionProvider`, which converts DTO models into business-ready models.
- Implemented conversion of business models into view models.
- Employed MVVM pattern for the implementation of the NFT collections catalog.

2023-05-31 15:48 UTC, AndreiChenchik requested changes
Все неплохо, немного подправить

2023-05-31 15:48 UTC, AndreiChenchik commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +        for viewModel in viewModel.viewModels ?? [] {
Wut? Надо как-то переименовать что-то куда-то ))

2023-05-31 15:48 UTC, AndreiChenchik commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
> +        switch option {
guard let бы, т.к. а что будет если одно будет работать, а другое нет? Не детерминирована логика

2023-05-31 15:48 UTC, AndreiChenchik commented on FakeNFT/Scenes/Collection/Cells/CatalogueCell.swift
> +        titleLabel.text = ("\(title) (\(nftCount))")
А внешние скобочки зачем? Запутать хочешь?)

2023-05-31 15:48 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/CollectionProvider.swift
> +                print("nftsData ERROR")
no print, gracias

2023-05-31 16:18 UTC, AndreiChenchik approved these changes
LGTM

2023-05-31 16:30 UTC, maxim-papier commented
Исправлено. Спасибо!

2023-06-01 18:47 UTC, IBDesignable requested changes

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Models/Collection/CollectionModels.swift
> +    }
хорошо

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Models/Collection/CollectionModels.swift
> +}
Я бы разнесла: каждую структуру в свой файл.

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +final class CatalogueVC: UIViewController {
Давай не будем сокращать ViewController

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +
точно нужно оставлять публичными?

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +    }
очень хорошо что модель инджектируется 👍🏻

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +            tableView.topAnchor.constraint(equalTo: guide.topAnchor, constant: 21),
Отступ 20. Но н
<img width="285" alt="Снимок экрана 2023-06-01 в 21 13 33" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/121577115/297c1ed4-a2df-4d87-86d1-ca8e9d3597f4">

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +        let guide = view.safeAreaLayoutGuide
очень круто что в отдельной переменной

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +            (tableView: UITableView, indexPath: IndexPath, viewModel: CatalogueVC.ViewModel) -> UITableViewCell? in
Дженерик тип компилятор выводит по декларации функции
```swift
        return UITableViewDiffableDataSource(tableView: tableView) {
            (tableView: UITableView, indexPath: IndexPath, viewModel: CatalogueVC.ViewModel) -> UITableViewCell? in
```

Параметры кложуры пишутся на той же строке с фигурной скобкой (swiftlint будет ругаться)
```swift
        return UITableViewDiffableDataSource(tableView: tableView) { (tableView: UITableView, indexPath: IndexPath, viewModel: CatalogueVC.ViewModel) -> UITableViewCell? in
```

Тип аргумента компилятор тоже выведет, полностью его писать не нужно

 ```swift
        return UITableViewDiffableDataSource(tableView: tableView) { tableView, indexPath, viewModel in
```

и вот мы уже почти влезаем в столбик 140 символов. Я бы тут остановилась, но можно кароче:

```suggestion
       return .init(tableView: tableView) { tableView, indexPath, viewModel in
```

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +            }
Тут тоже по длине не влезаем, поэтому предлагаю столбик так писать
```suggestion
            guard 
                let cell = tableView.dequeueReusableCell(
                    withIdentifier: CatalogueCell.identifier, 
                    for: indexPath
                ) as? CatalogueCell 
            else {
                return UITableViewCell()
            }
```

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +            cell.configure(title: viewModel.title, coverURL: viewModel.cover, nftCount: viewModel.nftsCount)
Тут на твой вкус, но я бы при большом количестве аргументов подумала об отдельной модели с данными

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +    @objc func didTapSortButton() {
тут точно нужен модификатор доступа

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
> +        switch option {
помечено как выполнено, но изменений нет

2023-06-01 18:47 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
> +                DispatchQueue.main.async { [weak self] in
у тебя получается что self в верхнем блоке сильно захватывается, нужно ослабить и там тоже.

Будет считаться ошибкой

2023-06-01 19:07 UTC, IBDesignable commented
Предполагали что вообще вся работа над эпиком будет делатся в одном пул-реквесте, чтобы видеть разницу между спринтами.

Я вижу что ваш процесс работы над дипломом устроен по-задачно, поэтому видимо этот ПР будет вмерджен. Будет круто если правки внесешь здесь(те что по задаче). И тегнешь этот пр в следующей сдаче остатков по эпику. Успехов, Максим!

2023-06-02 01:34 UTC, maxim-papier commented on FakeNFT/Models/Collection/CollectionModels.swift
> +}
Сделано. Спасибо.

2023-06-02 01:39 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +final class CatalogueVC: UIViewController {
Переименовал. Спасибо.

2023-06-02 01:43 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +            tableView.topAnchor.constraint(equalTo: guide.topAnchor, constant: 21),
Ох, бес попутал! Исправляю. Спасибо.

2023-06-02 01:44 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +    }
Спасибо. Пока такие привычки даются с усилием, но буду стараться.

2023-06-02 02:02 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +            (tableView: UITableView, indexPath: IndexPath, viewModel: CatalogueVC.ViewModel) -> UITableViewCell? in
Впечатляет! Спасибо

2023-06-02 02:04 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +            }
Сделано! Спасибо.

2023-06-02 02:04 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +    @objc func didTapSortButton() {
Буду внимательнее. Спасибо.

2023-06-02 02:07 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +        self.present(alert, animated: true, completion: nil)
Принято. Отложил в задачи.

2023-06-02 02:09 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +    func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat { 21 }
Возможно, всё же оно было раньше в макете. Я отмечал этот момент, когда проводил кросс-ревью согрупника. У него было 20, а в моих экранах 21. Но или ошибаюсь.

2023-06-02 02:18 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
> +    func sortModels(by option: SortOption) {
Действительно. Так красивее!

2023-06-02 02:22 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/CatalogueCell.swift
> +        label.textAlignment = .left
Да, упустил. Принято. Спасибо.

2023-06-02 02:28 UTC, maxim-papier commented on FakeNFT/TabBarControllerBuilder.swift
> +
Отложу в issues.

2023-06-02 02:31 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
> +}
Где-то подсмотрел такое название :) 🙂

2023-06-02 02:39 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +            cell.configure(title: viewModel.title, coverURL: viewModel.cover, nftCount: viewModel.nftsCount)
Спасибо. Понял!

2023-06-02 02:39 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueVC.swift
> +    }
Сделано. Вынес в CatalogueCellViewModel. Спасибо.

2023-06-02 02:40 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
> +                    self?.viewModels = collection.map { CatalogueVC.ViewModel($0) }
Принял. Сделал `CatalogueCellViewModel`

2023-06-02 02:58 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
> +                DispatchQueue.main.async { [weak self] in
Сделано

2023-06-02 03:12 UTC, maxim-papier commented on FakeNFT/Services/Collection/CollectionProvider.swift
> +final class CollectionProvider {
Действительно. Не подумал.

2023-06-02 03:37 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
> +                DispatchQueue.main.async { [weak self] in
Признаюсь, долго не мог понять. Надо будут повторить эту тему, чувствую, "что плаваю".  
Исправлено, спасибо.

2023-06-02 05:14 UTC, maxim-papier commented
> Я вижу что ваш процесс работы над дипломом устроен по-задачно, поэтому видимо этот ПР будет вмерджен. Будет круто если правки внесешь здесь(те что по задаче). И тегнешь этот пр в следующей сдаче остатков по эпику. Успехов, Максим!

Всё понял. Спасибо за ваши комментарии. 
Исправления по вашим замечаниям внёс. Парочку пришлось отложить на потом. 

PS. Касательно вашего комментария про вежливость во взаимодействии с одногруппниками, который вы оставили на платформе. Согласен, конечно. Мы просто в Zoom-созвоне обсудили их голосом. Буду внимательнее.

Ещё раз спасибо.

2023-06-02 05:16 UTC, maxim-papier commented
@IBDesignable могу вмёрдживать?

2023-06-02 06:34 UTC, merged