#12 shopping cart view
BlackBullSquad/iOS-FakeNFT-StarterProject-Public pull request #66
Opened 2023-05-31 19:27 UTC by AndreiChenchik

implementing #12

2023-06-01 03:41 UTC, maxim-papier commented
Похоже `vStack` надо по вертикали по центру аватарки выравнивать 
<img width="300" alt="Screenshot 2023-06-01 at 09 41 36" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/109724501/d74f4ba9-7a27-481f-8ea1-af268182b378">

2023-06-01 03:58 UTC, maxim-papier requested changes
Супер! Только vStask поправить https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/pull/66#issuecomment-1571284782

2023-06-01 13:35 UTC, AndreiChenchik commented
@maxim-papier пофиксил, доделал, смотри аппрувь :)

2023-06-01 14:30 UTC, maxim-papier approved these changes
Шик!

2023-06-02 01:31 UTC, maxim-papier commented
Мне очень понравилось. Придраться не к чему. Крут!

2023-06-02 16:04 UTC, ABashkirova requested changes

2023-06-03 19:18 UTC, AndreiChenchik commented
### От @ABashkirova 
#### 🐛 Что нужно исправить, чтобы двигаться дальше 
- [ ] UIKit, Foundation не хватило "При сетевых запросах блокируется интерфейс"
- [ ] Чистота кода проскочил один нелегальный force unwrap – нужно добавить обработку. 
- [ ] Архитектура есть серьезные ошибки в реализации: местами View делает больше работы чем надо, иногда работа с моделью происходит напрямую из вью (как хранение, так и взаимодействие). Не все экранны поддерживают архитектуру.
- [ ] Работа с сетевыми запросами: местами есть оставленные без обработки ошибки. Нужно решить как с ними поступать продуктово и доработать запросы
- [ ] Использование многопоточности для обработки ответа не продемонстрировано. Предполагается здесь наличие бекграудн очереди для сборки запроса/разборки ответа. 
- [ ] Работа с Git: здесь по большей части хорошо, но иногда проскальзывают комиты WIP - не понятно что там такое, такие коммиты до публичного репозитория не должны долетать.
- [ ] Автотестирование не продемонстрировано.

#### 🚀 Челенджи и что можно лучше
- [ ] Самый большой челендж для тебя это разрбраться с ответственностью у элементов MVVM, корректно собирать зависимости каждого. Ожидается что модель(сервисы, данные) являются зависимостью вьюмодели, а вьюмодель - единственная зависимость у вью. 
- [ ] Очень будет круто увидеть работу с добавленной ссылкой на вебвью.
- [ ] И также доработанные ассеты для темной темы: кажется там не очень много работы, чтобы поддержать эту допфичу. 

### От @maxim-papier 
- [ ] Когда открывается экран оплаты, в дизайне нету таббара.

2023-06-04 14:47 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartCell.swift
> +    func configure(_ viewModel: ItemViewModel?, onDelete: (() -> Void)?) {
Исправлено!

2023-06-04 14:48 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ItemViewModel.swift
> +    }
Да, в данном случае действительно это было бы лучше, чтобы отвязаться от UIKit. Исправлено.

2023-06-04 14:49 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/Dependencies.swift
> +    }
Да, это нужно в VM, перенес.

2023-06-04 14:49 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/DeleteController.swift
> +
Все исправил :)

2023-06-04 14:50 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartCell.swift
> +        guard let priceFormatter else { preconditionFailure("cell was not set up properly") }
Да, действительно, так понятнее будет.

2023-06-04 14:50 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +    }()
Да, теперь они на месте :)

2023-06-04 14:51 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +    }
Прибрал в структурах :) Теперь лучше

2023-06-04 14:51 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +    let tableView = UITableView()
Просто забыл, спасибо за напоминание :) Теперь спрятал

2023-06-04 14:53 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +            tableView.topAnchor.constraint(equalTo: guide.topAnchor, constant: 21),
Просто уровень доверия к команде 100 из 100 🤣

2023-06-04 14:53 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +        buttonPanel.isHidden = viewModel.nftCount == 0
Согласен, исправлено

2023-06-04 14:53 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +}
Исправлено

2023-06-04 14:54 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectCell.swift
> +    }
Спасибо :)

2023-06-04 14:54 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectCell.swift
> +        }
Разобрался, не знаю зачем это я так, спешил :)

2023-06-04 14:55 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectController.swift
> +
Беда миновала, поправил :)

2023-06-04 14:56 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectController.swift
> +    @objc func didTapPurchaseButton() {
Поисправлял! Спасибо

2023-06-04 14:56 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/PurchaseStatusController.swift
> +    }
Теперь есть 🤗

2023-06-04 14:59 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +    }
Да, непонятно, из-за этого невозможно выйти на model-only уровень и просто логику смотреть. Исправил!

2023-06-04 15:05 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +            purchaseButton.widthAnchor.constraint(equalToConstant: 240)
@ABashkirova Тут что-то непонятно, так у меня сначала было, но в этом случае когда цена меняется у нас все начинает некрасиво ездить, считаю это не оптимальным вариантом. Тут прям надо фиксировать что-то, можно на процент экрана. Мне кажется тут надо @x128 перетереть с дизайнером и решить что делать. Продублирую в пачке

2023-06-04 15:12 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartCell.swift
> +
С ифами разобрался, а отсутствие вью модели так обусловлено
- Инициализация ячейки происходит без viewModel, ведь ее инициализирует коллекция/таблица, а nil это по сути дефолтная модель
- Ячейку нужно ресетить, тут пустая модель тоже подходит
- Модель обновляется вся сразу, поэтому можно упростить биндинг до { didSet } 

Т.е. по сути можно было бы сделать 
```
enum ViewModelState {
    case .empty
    case .active(ViewModel)
}
```

Но это же прям и есть `.none`/`.some` у `Optional`, так что тут я специально выбрал опциональное значение

@ABashkirova прокатит? 😉

2023-06-04 15:13 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +        let deleteController = DeleteController(avatarURL: model.avatarUrl!) { [weak self] in
Теперь форс анврапа нет

2023-06-04 19:36 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectCell.swift
> +        contentView.layer.borderWidth = viewModel.isSelected ? 1 : 0
Ну тут да, я тут скорее еще про вью сам думаю, типа где бы я хотел выставлять толщину обводки? Явно не во вью модели :)

2023-06-04 20:44 UTC, x128 commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +            purchaseButton.widthAnchor.constraint(equalToConstant: 240)
Привет :) думаю, Саша имеет в виду, что надо не кнопке ставить 240, а отступ слева фиксированный 119

Размер кнопки получится как раз фиксированный, просто разный для разных экранов

2023-06-04 21:00 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +            purchaseButton.widthAnchor.constraint(equalToConstant: 240)
> Привет :) думаю, Саша имеет в виду, что надо не кнопке ставить 240, а отступ слева фиксированный 119
> 
> Размер кнопки получится как раз фиксированный, просто разный для разных экранов

Так тоже хорошо, альтернативный вариант, но опять не по дизайну :) Там Hug

2023-06-04 21:00 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +            tableView.topAnchor.constraint(equalTo: guide.topAnchor, constant: 21),
Исправлено

2023-06-04 21:17 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectController.swift
> +        collection.contentInset = .init(top: 20, left: 0, bottom: 0, right: 0)
Да, действительно, исправил, там правда дизайнер вообще этого не ожидает, так что одного меня не хватит, но я передал ему сообщение :)

2023-06-04 21:23 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +            purchaseButton.widthAnchor.constraint(equalToConstant: 240)
Исправил!

2023-06-04 21:26 UTC, x128 commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +            purchaseButton.widthAnchor.constraint(equalToConstant: 240)
Точно, у контейнера с ценой же Hug.
Нипанятна, отнёс дизайнеру

2023-06-05 18:27 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +                print(error)
Теперь хорошо все, исправил!

2023-06-05 18:28 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectController.swift
> +
Теперь кликабельно :)

2023-06-05 18:42 UTC, AndreiChenchik commented
@ABashkirova осталось два пункта нужны уточнения:

> Использование многопоточности для обработки ответа не продемонстрировано. Предполагается здесь наличие бекграудн очереди для сборки запроса/разборки ответа.

Тут я по критериям говорят про гонки, которые при блокировке интерфейса в целом можно +- избежать, а дальше URLSession работает в бэкграунде и пока ты не получил нужные данные просто не надо оттуда выходить в DQMain. Не очень понятно что тут еще делать? 

> Автотестирование не продемонстрировано.

Вроде это не обязательно, нет?

2023-06-06 06:03 UTC, IBDesignable commented
> Не очень понятно что тут еще делать? 

Уточни пожалуйста у Наставника, пока у меня информация именно такая: да запрос отправляется на очереди с URLSession, но сам процесс запекания запроса и его парсинга можно положить в свою бекграунд очередь. Выглядит натужно, согласна. Приму аргумент согласованный с Наставником 

> Автотестирование не продемонстрировано. Вроде это не обязательно, нет? 

Все верно, все так. 


@AndreiChenchik работу смогу отдать обратно  только завтра – технические проблемы с первой сданной работой. Комментарии в ПР появятся сегодня.

2023-06-06 11:42 UTC, AndreiChenchik commented
@IBDesignable спасибо! 
@x128 ожидаю твой комментарий по поводу потоков, тут еще усложняет тот факт, что парсинг запроса происходит распаковщиком codable, который был предоставлен, можно его конечно поменять, но сомневаюсь что в этом была идея. А прокинуть три Intа в struct на этапе формирования запроса... это прям вообще хз... мне вообще кажется что компилятор это заинлайнит и там просто нечего перемещать между очередями.

2023-06-06 13:35 UTC, maxim-papier approved these changes

2023-06-06 14:27 UTC, x128 commented
> @x128 ожидаю твой комментарий по поводу потоков, тут еще усложняет тот факт, что парсинг запроса происходит распаковщиком codable, который был предоставлен, можно его конечно поменять, но сомневаюсь что в этом была идея. 

Угу, препятствие с парсингом в том, что надо модифицировать исходную авторскую заготовку. Предлагаю это не делать. Вероятны мерж-конфликты с коллегами. А для будущих когорт получше продумаем.

> А прокинуть три Intа в struct на этапе формирования запроса... это прям вообще хз... мне вообще кажется что компилятор это заинлайнит и там просто нечего перемещать между очередями.

При возможности можно сделать для тренировки, т.к. на реальном проекте параметры запроса могут собираться из многих разных источников, или какой-нибудь хедер с асинхронным шифрованием. @IBDesignable о кстати, а это как раз идея на тему, чё можно добавить в ТЗ по-быстрому :)

2023-06-06 16:05 UTC, AndreiChenchik commented
@x128 @ABashkirova @IBDesignable спасибо, я тогда вычеркиваю оба пункта :) Есть что доделать другое, по другим проектам.

2023-06-06 18:07 UTC, ABashkirova commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartCell.swift
> +
я бы сказала, что это избыточная заморочность))
у тебя ячейка без этой вьюмодели в космос не полетит, бесполезна без нее. В моих рабочих проектах никто особо не сбрасывает все элементы. Только тяжелые – типа картинок, но надо признать мы и не мерили, может это и оптимальное решение с точки зрения перформанса

2023-06-06 19:20 UTC, ABashkirova requested changes
Пока из критичных только два форса на глаза попались, да неочевидное отсутствие  перехода на мейн очередь при байдинге данных и затесавшийся ui-код во вью модельке. 

Завтра еще досмотрю этот пункт и допишу полное ревью на платформе. Можно не тратить доп итерацию на фиксы, а сделать это до завтрашнего полудня мск. 

Спасибо за ответы на ревью – очень радуюсь, когда комментарии не были в пустоту оставлены 🙏🏻

2023-06-06 19:20 UTC, ABashkirova commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/ShoppingCartCell/ShoppingCartCellViewModel.swift
> +    var priceLabel: String { "\(deps.priceFormatter.string(from: .init(value: price))!) ETH" }
ну заленился же. давай свойство по умолчанию либо опциональный лебел

2023-06-06 19:20 UTC, ABashkirova commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/ShoppingCartViewModel.swift
> +        UIBlockingProgressHUD.show()
а чего это UI во ViewModel залез? непорядки

2023-06-06 19:20 UTC, ABashkirova commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/ShoppingCartViewModel.swift
> +        UIBlockingProgressHUD.show()
тут уж увы, MVVM такая, нужно свойство обсервить isLoading

2023-06-06 19:20 UTC, ABashkirova commented on FakeNFT/Scenes/Web/WebView.swift
> +    }
ай яй, super пропущен

2023-06-06 19:20 UTC, ABashkirova commented on TODO.md
> +- [x] Внести правки спринта 19, eta 1:00, spent 5:00
💔❤️‍🩹

2023-06-06 19:20 UTC, ABashkirova commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/ShoppingCartViewModel.swift
> +    var priceLabel: String { "\(deps.priceFormatter.string(from: .init(value: totalPrice))!) ETH" }
👀!

2023-06-06 19:20 UTC, ABashkirova commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectViewModel.swift
> +                )
А я вот кстати не поняла, каким образом после получения ответа от сервисов и провайдеров, ты переходишь на главную очередь?

По коду совсем не очевидно и как будто бы надо все таки тред на мейн сменить (удивительно что это типо работает)

2023-06-06 19:20 UTC, ABashkirova requested changes
Пока из критичных только два форса на глаза попались, да неочевидное отсутствие  перехода на мейн очередь при байдинге данных и затесавшийся ui-код во вью модельке. 

Завтра еще досмотрю этот пункт и допишу полное ревью на платформе. Можно не тратить доп итерацию на фиксы, а сделать это до завтрашнего полудня мск.

2023-06-07 20:44 UTC, IBDesignable commented
[Andrei Chenchik – Ревью диплома.pdf](https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/files/11681798/Andrei.Chenchik.pdf)

2023-06-07 21:04 UTC, AndreiChenchik commented on FakeNFT/DesignSystem/Colors.swift
> +
@ABashkirova вообще был такой план, просто времени не хватало, но сделал раз уж в глаза бросилось.
Кстати скоро уже и не надо будет этого делать, завезли же макросы!

Исправлено :)

2023-06-07 21:10 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectCell/CurrencySelectCellView.swift
> +        )
Попробовал сделать и действительно выглядит намного понятнее. Спасибо!

Исправлено :)

2023-06-07 21:12 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectView.swift
> +        )
Я глядел на этот ад, когда пытался понять как это пофиксить, глядел и забил. Но вижу, что на SE беда :) Сейчас посмотрю что можно сделать.

2023-06-07 21:15 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectView.swift
>          firstLine.textAlignment = .left
Ого, я не знал и накопипастил это везде :) Спасибо!
Исправлено

2023-06-07 21:17 UTC, AndreiChenchik commented on FakeNFT/Scenes/Web/WebView.swift
> +    }
Вот это я заспешил! Спасибо
Исправлено

2023-06-07 21:20 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/ShoppingCartViewModel.swift
> +    var priceLabel: String { "\(deps.priceFormatter.string(from: .init(value: totalPrice))!) ETH" }
oops! fixed

2023-06-07 21:22 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/NftDelete/NftDeleteViewModel.swift
> +final class NftDeleteViewModel: ObservableObject {
Боюсь будем еще зарубаться на мёрдже :D Но уделим внимание этому

2023-06-07 21:25 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/ShoppingCartCell/ShoppingCartCellViewModel.swift
> +    var priceLabel: String { "\(deps.priceFormatter.string(from: .init(value: price))!) ETH" }
Дэээ, заленился, но вообще тут конечно я не очень понимаю что может не получиться у форматера, если я знаю что ему точно передаю Float.. Ну т.е. это прям странное API. Энивей - исправил на дефолт

2023-06-07 21:27 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectViewModel.swift
> +                )
у меня там bind на главную очередь кидает, т.е. любой апдейт модели тригерит с главной очереди апдейт UI 

```swift
extension ObservableObject {
    func bind(onUpdate: @escaping () -> Void) -> AnyCancellable {
        self
            .objectWillChange
            .receive(on: DispatchQueue.main)
            .sink { _ in
                onUpdate()
            }
    }
}
```

2023-06-07 21:30 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/PurchaseCoordinator.swift
> +            ) {}
Да, действительно кривенько получается :) 
Исправил

2023-06-07 21:39 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectViewModel.swift
> +        }
Одна из самых мутных функций всего проекта, я и так и сяк ее переделывал, все криво как-то было. 
Теперь лучше, теперь прибрал.

2023-06-08 06:01 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/NftDelete/NftDeleteViewModel.swift
> +final class NftDeleteViewModel: ObservableObject {
А вот теперь договорились - camel case Nft :)

2023-06-08 19:57 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectViewModel.swift
> +                )
Что-то вроде @MainActor :) получилось, необычно, но явно.

2023-06-08 19:57 UTC, AndreiChenchik commented on TODO.md
> +- [x] Внести правки спринта 19, eta 1:00, spent 5:00
Штош... еще немного придется накинуть :)

2023-06-08 20:15 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/CurrencySelect/CurrencySelectView.swift
> +        )
Исправил!

2023-06-08 20:28 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/ShoppingCart/ShoppingCartViewModel.swift
> +        UIBlockingProgressHUD.show()
Дааа... 
Исправил, теперь ну совсем чистота :D Еще немного и будет свифтюай

2023-06-08 20:39 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/PurchaseCoordinator.swift
> +            defer { UIBlockingProgressHUD.dismiss() }
Исправил, ну теперь вообще красота!

2023-06-08 20:42 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartCell.swift
> +
Понял, ну я немного перестарался :)) Пусть будет как джунский загон))

2023-06-08 20:43 UTC, AndreiChenchik commented on FakeNFT/Scenes/ShoppingCart/Cart/ShoppingCartController.swift
> +            purchaseButton.widthAnchor.constraint(equalToConstant: 240)
Ну, вроде новых идей не появилось, резолвлю как есть, работает и не прыгает, кнопка даже немного расширяется в зависимости от экрана. Не ясно что тут лучше можно придумать :)

2023-06-19 19:05 UTC, AndreiChenchik commented
Ура! Все конфликты исправлены. Эта последняя ветка на мёрдж. Дальше будем отправлять на ревью еще раз с видосами!

Спасибо @maxim-papier @IBDesignable @x128 @ABashkirova @Filosuf

2023-06-19 19:06 UTC, merged