Collections sprint 20
BlackBullSquad/iOS-FakeNFT-StarterProject-Public pull request #84
Opened 2023-06-06 14:13 UTC by maxim-papier

2023-06-07 08:41 UTC, AndreiChenchik approved these changes
Круто! Проверил, работает. Накидал рекомендаций

2023-06-07 08:41 UTC, AndreiChenchik commented on Catalogue-Epic-Plan.md
Рекомендация: Таки перенести весь контент в общий туду

2023-06-07 08:41 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/CollectionsSortOptionPersistenceService.swift
> +        let encoder = JSONEncoder()
устанет сервис пересоздавать энкодеры, это такая же зависимость как UserDefaults, можно создавать один раз

2023-06-07 08:41 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/CollectionsSortOptionPersistenceService.swift
> +        let decoder = JSONDecoder()
Аналогично с энкодером

2023-06-07 08:41 UTC, AndreiChenchik commented on FakeNFT/Scenes/Collection/Cells/CollectionCellViewModel.swift
> +    var authorLinkTapped: ((URL) -> Void)
А это тут надо? Что-то такое ощущение, что переехало от описания

2023-06-07 08:41 UTC, AndreiChenchik commented on FakeNFT/Scenes/Collection/Cells/CoverCell.swift
> +    var viewModel: CollectionCellViewModel? {
Я запутался какая ячейка от какой модели зависит, CollectionCell зависит от NftCellViewModel, но CoverCell зависит от CollectionCellViewModel?

2023-06-07 08:41 UTC, AndreiChenchik commented on FakeNFT/Scenes/Collection/Cells/DescriptionCell.swift
> +    var viewModel: CollectionCellViewModel? {
Одна вью модель работает на один тип вью, а не одна вью модель под вообще всё

2023-06-07 08:41 UTC, AndreiChenchik commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
>      func loadCollections() {
рекомендация: вынести в провайдер, а вьюмодель использовать как точку сборки

2023-06-07 08:41 UTC, AndreiChenchik approved these changes
Круто! Проверил, работает. Накидал рекомендаций

2023-06-07 08:43 UTC, AndreiChenchik requested changes
Ой, дал аппрув, а мёржить же только после ревью от ревьювера

2023-06-08 01:04 UTC, maxim-papier commented on Catalogue-Epic-Plan.md
Спасибо!

2023-06-08 01:09 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueView.swift
- [ ] Убрать ProgressHUD
- [ ] Исправить constraints в сцене Collection

2023-06-08 01:11 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueView.swift
Ещё ничего не правил, а вёрстка Catalogue сломалась. 
<img width="478" alt="Screenshot 2023-06-08 at 07 10 00" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/109724501/a3de82e1-2a7f-4112-890c-1464ba9d2150">

- [ ] Исправить constraints в сцене Catalogue

2023-06-08 09:18 UTC, maxim-papier commented on FakeNFT/Services/Collection/CollectionsSortOptionPersistenceService.swift
> +        let encoder = JSONEncoder()
Переделано. Спасибо.

2023-06-08 09:18 UTC, maxim-papier commented on FakeNFT/Services/Collection/CollectionsSortOptionPersistenceService.swift
> +        let decoder = JSONDecoder()
Аналогично переделано.

2023-06-08 09:19 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueView.swift
Переделано, а потом ещё раз, после того как сменилось ТЗ.

2023-06-08 09:19 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueView.swift
Спасибо!

2023-06-08 09:20 UTC, maxim-papier commented on Catalogue-Epic-Plan.md
Отдельный файл создан с таким названием по задаче ревьюера.

2023-06-08 09:26 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/CoverCell.swift
> +    var viewModel: CollectionCellViewModel? {
Переделал немного. 

Ячейки:
- `CollectionDetailsNftListCellView`
- `CollectionDetailsCoverCellView`
- `CollectionDetailsDescriptionCellView`

Зависят от:
- `CollectionDetailsCellViewModel`

Тут выходит следующее: все эти ячейки относятся к одной коллекции NFT и все переиспользуются в одном `CollectionDetailsView`. Кажется разумным этим ячейкам работать с одной вьюмоделью.

2023-06-08 09:33 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
>      func loadCollections() {
> Ой, дал аппрув, а мёржить же только после ревью от ревьювера
Конечно. После того как я однажды уничтожил `develop` я буду очень аккуратен. :)

2023-06-08 09:34 UTC, maxim-papier commented
> Ой, дал аппрув, а мёржить же только после ревью от ревьювера

Конечно. После того как я однажды уничтожил develop я буду очень аккуратен. :)

2023-06-08 10:23 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
>      func loadCollections() {
Ощущение, что оно же практически так и есть у меня — точка сборки. Не так?

2023-06-09 04:36 UTC, maxim-papier commented
Обнаружил глюк вывода ячеек NFT-коллекции при переиспользовании. Проблема возникала из-за  спейсера, который был создан в ячейке. Компенсировал удаление спейсера в ячейки увеличенным расстоянием между группами в `UICollectionView` в секции `.collection`. 

<img width="474" alt="Screenshot 2023-06-09 at 10 25 28" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/109724501/070461fd-a35c-4c3c-9b0d-3a3bee698ef9">

2023-06-10 08:59 UTC, ABashkirova reviewed
Нужно доправить верстку: в макете нет белого навбара. В этой ситуации можно попробовать слелать его прозрачным, но мне кажется выгрышнее будет кнопку поверх экрана сделать, а навбар прятать.
<img width="511" alt="Снимок экрана 2023-06-10 в 10 35 43" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/20269264/ec822437-3fe4-42ca-a38a-9a4a4b46aaa4">

На главном тоже видно системный навбар, хотя в макетах там нет тени и цвет шапки совпадает с цветом фона

<img width="511" alt="Снимок экрана 2023-06-10 в 10 37 49" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/20269264/68cf4576-d323-4c86-ba4c-c3cab11be606">

В ТЗ есть два немного противоречивых момента в твоем эпике:

> При нажатии на ячейку открывается экран NFT.
> **Экран NFT**
> Экран частично реализуется наставником в ходе life coding. Реализация экрана студентами не требуется.

У тебя нет активного поведения на нажатие у элемента коллекции: тут ожидаемое поведение открытый экран НФТ. 
Но при этом делать тебе его не нужно было. В таком случае, в разработке делаются две вещи: выполняется ТЗ полностью, как указано требование (переход на экран - можно заглушку), второе – задаем вопрос заказчику: типо где экран, кто мне его выдаст и когда. 
Это замечание про софтскиллы, исправлять и добавлять переход не требуется.

Еще два пункта, которые на мой взгляд не реализованы:

- При нажатии на кнопку добавления NFT в корзину / удаления NFT из корзины производится добавление или удаление NFT из заказа (корзины).  
- При нажатии на сердечко производится добавление NFT в избранное / удаление NFT из избранного. 

Здесь логика похоже неверное работает: ты можешь нажать на кнопки, но при скроле вперед-назад, состояние у ячеек сбрасывается/или неверно переиспользуется. Судя по всему – модель локально не обновилась.
Кроме того: здесь ожидаются запросы на бек, на изменение состояние коллекции. и между сессиями это состояние должно сохраняться. Здесь нужно посоветоваться с коллегами и Наставником, и задачу добить любым возможным способом. 
Обрати внимание на баг на видео: лайки пропадают, иконка корзины появляется в рандомных местах:
https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/20269264/6a2675a5-531e-4216-9877-4f07515d842a


[Максим Брыков - Ревью диплома.pdf](https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/files/11712049/-.pdf)

2023-06-10 08:59 UTC, ABashkirova commented on FakeNFT/DesignSystem/NftAvatarView.swift
> +        viewModel?.isLiked.toggle()
вот это действие не относится к слою View: тоглить или нет, должна думать модель по действию likeButtonAction (didLike или onLike - нейминг лучше передает происходящее)

2023-06-10 08:59 UTC, ABashkirova commented on FakeNFT/DesignSystem/NftAvatarView.swift
> +final class NftAvatarView: UIView {
У тебя в проекте NFTAvatarView и NftAvatarView – надо определиться, непонятно почему оно так осталось

2023-06-10 08:59 UTC, ABashkirova commented on FakeNFT/Scenes/Collection/Cells/Views/CollectionDetailsNftListCellView.swift
> +            likeButtonAction: { return }
а реализовать запрос на бекенд?

2023-06-10 08:59 UTC, ABashkirova commented on FakeNFT/Scenes/Collection/Cells/Views/CollectionDetailsNftListCellView.swift
> +            isLiked: false,
да и вообще похоже что лайк почему-то с сервера не дополучил

2023-06-10 08:59 UTC, ABashkirova commented on FakeNFT/Scenes/Collection/Cells/Views/CollectionDetailsNftListCellView.swift
> +            likeButtonAction: { return }
нужно доделать. 

Ну и return писать не обязательно в войдовом замыкании, можно просто { } – в тестах или заглушках так можно.

2023-06-10 08:59 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/CollectionDetails/CollectionDetailsViewModel.swift
> +                assertionFailure("\(error)")
assertionFailure – не обработанная ошибка. Если делать множественные запросы экранов, мок сервер перестает отвечать похоже и приложение падает, вместо того чтобы показать ошибку. 

Это нужно исправить

2023-06-10 08:59 UTC, IBDesignable commented on FakeNFT/Scenes/Collection/CollectionDetails/CollectionDetailsViewModel.swift
> +                assertionFailure("\(error)")
<img width="1276" alt="Снимок экрана 2023-06-10 в 11 37 35" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/121577115/ae84d1f6-11bb-470e-bcb2-27441110e599">

2023-06-10 09:01 UTC, IBDesignable commented
Прошу прощения за долгое ожидание – проверка занимает больше ожидаемого времени

2023-06-10 09:01 UTC, IBDesignable commented
Комментарий про растующую память: будет круто если разберешься с кэшем картиночек
![Uploading Снимок экрана 2023-06-10 в 11.39.26.png…]()

2023-06-10 09:17 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/Views/CollectionDetailsNftListCellView.swift
> +            likeButtonAction: { return }
> Прошу прощения за долгое ожидание – проверка занимает больше ожидаемого времени 🙈

Всё хорошо. Представляю, сколько сейчас у вас ревью. Спасибо. Хорошего дня!

2023-06-10 12:03 UTC, maxim-papier commented on FakeNFT/TabBarControllerBuilder.swift
> +        guard let collectionsCoordinator = collectionsCoordinator else {
Спасибо. Сделал неопциональным.

2023-06-10 14:31 UTC, maxim-papier commented
> Прошу прощения за долгое ожидание – проверка занимает больше ожидаемого времени 🙈
Всё хорошо. Я понимаю сколько у вас сейчас забот.

2023-06-11 02:12 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/CollectionDetails/CollectionDetailsView.swift
> +
Спасибо. Сделано: https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/pull/84/commits/e71924ca96e640af020e201d46e5b530dab03f93

2023-06-11 02:14 UTC, maxim-papier commented on FakeNFT/Services/Collection/CollectionsSortOptionPersistenceService.swift
> +    private let sortOptionKey = "SortOptionKey"
Да, действительно. Как сам не догадался?! Спасибо.

2023-06-11 02:48 UTC, maxim-papier commented
> Комментарий про растующую память: будет круто если разберешься с кэшем картиночек
> 
> <img alt="Снимок экрана 2023-06-10 в 11 39 26" width="1182" src="https://user-images.githubusercontent.com/121577115/244860845-c6c7b677-fcd7-411f-8ba1-ed20161a154a.png">
Я с тревогой смотрел на этот график. Но ведь `Kingfisher` должен был всё закешировать?

2023-06-11 02:54 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/CollectionDetails/CollectionDetailsView.swift
> +    }
Теперь пригодился, чтобы прятать `Tabbar` :)

2023-06-11 03:01 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/CollectionDetails/CollectionDetailsView.swift
> +        }()
Согласен. Увлёкся что-то. Пофиксил — https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/pull/84/commits/434637677a5564c4f14e78cc71b6b342aba8c007
Спасибо.

2023-06-11 03:05 UTC, maxim-papier commented on FakeNFT/DesignSystem/NftAvatarView.swift
> +final class NftAvatarView: UIView {
Глюк `git`. В команде договорились исправить нейминг с NFT, на Nft. Спасибо!

2023-06-11 04:34 UTC, maxim-papier commented
@IBDesignable договорились с `наставником`, что после того как всё будет замерджено другими участиками команды, мне надо будет реализовать взаимодействие с их слоями — с корзиной и избранным в профиле.

2023-06-11 04:55 UTC, maxim-papier commented on FakeNFT/DesignSystem/RatingView.swift
> +    var rating: Int? { didSet { configure(with: rating) } }
Это классный код. Но, к сожалению, не мой. Мы распределили дизайн-систему в команде. Рейтинг делал Андрей — ему и лавры 👍

2023-06-11 04:57 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/Views/CollectionDetailsNftListCellView.swift
> +
Перенёс из приватного метода и забыл спрятать. Извиняюсь.

2023-06-11 07:14 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/CollectionDetails/CollectionDetailsViewModel.swift
> +                assertionFailure("\(error)")
Сделано: https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/tree/754a06b8a923e16abaa5b4f7211d50995e9cea6b Спасибо

2023-06-11 07:25 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Catalogue/CatalogueViewModel.swift
>      func loadCollections() {
Не додумался. Спасибо.

2023-06-11 07:26 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/Views/CollectionDetailsNftListCellView.swift
> +    private var isInCart: Bool = false
Это заглушка, пока нет доступа к сервису от коллег

2023-06-11 07:27 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/Views/CollectionDetailsNftListCellView.swift
> +            isLiked: false,
Заглушка, пока нет сервиса от коллеги

2023-06-11 08:05 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/Views/CollectionDetailsNftListCellView.swift
> +final class CollectionDetailsNftListCellView: UICollectionViewCell {
Сделано, но пока с заглушкам под лайки и корзину

2023-06-11 08:11 UTC, maxim-papier commented
@IBDesignable о пункте:
❌ Пагинация в необходимых местах работает корректно — нет множественных запросов с одними и теми же параметрами, показывается «крутилка». 

Не придумал где можно реализовать пагинацию (она в дизайне отсутствует). С крутилкой тоже не ясно, разве что при сортировке, но у меня там реализована классная анимация ячеек. 

Как мне исправить этот пункт?

2023-06-11 12:53 UTC, maxim-papier commented
Добавлена крутилка при загрузке каталога и коллекции — https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/pull/84/commits/eaa80ef1db21e6a79fe8c159fb0dcb85c6677a94

2023-06-11 14:53 UTC, maxim-papier commented
> > Комментарий про растующую память: будет круто если разберешься с кэшем картиночек
> > <img alt="Снимок экрана 2023-06-10 в 11 39 26" width="1182" src="https://user-images.githubusercontent.com/121577115/244860845-c6c7b677-fcd7-411f-8ba1-ed20161a154a.png">
> 
> Я с тревогой смотрел на этот график. Но ведь `Kingfisher` должен был всё закешировать? Когда второй раз загружаю, то уже видно, что кэш используется. Или тут надо как-то иначе действовать?

@IBDesignable понял, у `Kingfisher` гибридный кэш — и диск, и память. Сделал дисковому 512 MB, а тому, что в памяти — 128 MB, но почему-то память по-прежнему уходит 👎

2023-06-13 09:24 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +            guard self != nil else { return }
странно почему ты не проверяешь guard let self else { return }, и зачем ты вообще это делаешь если дальше не используешь self?

2023-06-13 09:24 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +                self.api.updateProfile(
А тут self испрользуешь но не не делаешь [weak self]

2023-06-13 09:24 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +    func getLikes(userID: Int, completion: @escaping (Result<[Int], ApplicationError>) -> Void)
А нужен ли тебе такой сервис где ты должен знать юзер айди? Я не уверен. Т.е. все экраны которые захотят загрузить лайки должны будут знать айди пользователя... Даже маленькая вьюшка. Возможно тебе стоит иметь какой-то UserProvider внутри конкретной реализации NftLikesProviderProtocol, который тебе даст инфу о пользователе текущем, т.е. в протоколе как бы это не надо. Но это конечно мечты :) Возможно на данном этапе уже поздно об этом думать.

2023-06-13 09:24 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +    func updateLikes(userID: Int, likes: [Int], completion: @escaping (Result<Void, ApplicationError>) -> Void)
Вместо Int можно было бы использовать Nft.ID, User.ID, тогда в случае изменения модели - мы сразу поймем где нестыковочка, ну и читать проще. По сути в данный момент Nft.ID является typealias к Int, потому что Nft у нас Identifiable и имеет var id: Int.

2023-06-13 09:24 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +protocol NftLikesProviderProtocol {
А тут не нужен еще один простой метод isLiked(_ nftId: Nft.ID) ? Чтобы просто спрашивать у сервиса нужно ли показывать сердечко.

2023-06-13 09:27 UTC, AndreiChenchik commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +    func getLikes(userID: Int, completion: @escaping (Result<[Int], ApplicationError>) -> Void)
Сложно натянуть это на какой-то принцип, но потенциально это про https://en.wikipedia.org/wiki/Interface_segregation_principle

Т.е. надо описывать протоколы максимально близко к тому, что тебе надо, в идеале не думая как там их будут реализовывать, пусть дальше по пищевой цепочке мучаются, у тебя во вью моделях и так достаточно обязанностей

2023-06-13 09:38 UTC, maxim-papier commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +            guard self != nil else { return }
Спасибо. Последствие невнимательности. Был огромный метод, разбирал его на части и пропустил.

2023-06-13 09:38 UTC, maxim-papier commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +                self.api.updateProfile(
Спасибо. Последствие невнимательности. Был огромный метод, разбирал его на части и пропустил.

2023-06-13 09:40 UTC, maxim-papier commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +    func getLikes(userID: Int, completion: @escaping (Result<[Int], ApplicationError>) -> Void)
Вау! Очень познавательная ссылка. 

Тут просто всё моковое и юзер один... Можно пока так, а?))

2023-06-13 09:42 UTC, maxim-papier commented on FakeNFT/Services/Collection/NftLikesProvider.swift
> +    func updateLikes(userID: Int, likes: [Int], completion: @escaping (Result<Void, ApplicationError>) -> Void)
Это очень красивое замечание! СПАСИБО

2023-06-13 10:00 UTC, maxim-papier commented
Исправления по ревью внесены. В том числе интегрирован сервис корзины и сделан свой сервис для получения лайков. 

https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/blob/22a694e5d19121688a8afd1e5629c854b7b024b9/Catalogue-Epic-Plan.md?plain=1#L74-L82

2023-06-14 08:07 UTC, IBDesignable approved these changes
[Максим Брыков - Ревью диплома 2it.pdf](https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/files/11743228/-.2it.pdf)

Получи еще апрув в пулреквесте от Андрея(сейчас реджект стоит)

Работу допускаю до общего мерджа! Спасибо за исправления, ты хорошо постарался!

Обрати внимание: есть еще бажок при работе с загрузкой данных, можно попасть в тупик с белым экраном. Будет круто если разберешься – если нет, ну останется баг в продакшене как в жизни)

2023-06-14 08:08 UTC, IBDesignable commented
> Ой, дал аппрув, а мёржить же только после ревью от ревьювера

@AndreiChenchik да можно апрув ставить, но мерджа низя делать) поставь плез сейчас)

2023-06-14 08:29 UTC, maxim-papier commented on FakeNFT/Assets.xcassets/AppIcon.appiconset/1024x1024@1x.png
Действительно. Дизайнерской прошлое взяло верх. Не подумал. Извиняюсь.

2023-06-14 08:48 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/ViewModels/CoverAndDescriptionCellsViewModel.swift
> +struct CoverAndDescriptionCellsViewModel {
Действительно, одна вьюмодель была на две ячейки. Не ясно почему — бес попутал. Прошу прощения. Исправил.

2023-06-14 08:49 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/ViewModels/NftListViewModel.swift
> +        self.nftCellViewModels = nfts.map { nft -> NftCellViewModel in
Спасибо!

2023-06-14 08:50 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/Cells/Views/NftListView.swift
> +        didUpdateViewModel()
Спасибо. Буду учиться!

2023-06-14 08:52 UTC, maxim-papier commented on FakeNFT/Scenes/Collection/CollectionDetails/CollectionDetailsViewModel.swift
> +            }
Спасибо. Исправил.

2023-06-14 08:59 UTC, maxim-papier commented on FakeNFT/Services/LogService.swift
> +}
Спасибо. Скажу честно, очень хотелось его вам показать :) Сделал приватный `init()`

2023-06-14 09:06 UTC, maxim-papier commented on FakeNFT/Services/ImageCacheService.swift
> +        ImageCache.default.diskStorage.config.sizeLimit = diskCacheSize
Я проверил разные размеры кэша, а вот про колличественные и временные параметры не знал! Спасибо, испытаю.

2023-06-14 09:10 UTC, maxim-papier commented
> [Максим Брыков - Ревью диплома 2it.pdf](https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/files/11743228/-.2it.pdf)
> 
> Получи еще апрув в пулреквесте от Андрея(сейчас реджект стоит)
> 
> Работу допускаю до общего мерджа! Спасибо за исправления, ты хорошо постарался!
> 
> Обрати внимание: есть еще бажок при работе с загрузкой данных, можно попасть в тупик с белым экраном. Будет круто если разберешься – если нет, ну останется баг в продакшене как в жизни)

Большое спасибо вам. Ваши ревью лучшие из всех, что я встречал за год, как встал на путь разработчика. Скажу более, иногда я что-то делаю и думаю: "А что на это скажет Александра?". 🙃Думаю, что это теперь со мной навсегда.

Буду стараться и впредь! ✌️

2023-06-14 10:32 UTC, AndreiChenchik approved these changes

2023-06-19 11:52 UTC, maxim-papier commented
https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/blob/8f1f47e5bb89f109c30ca18c0dcf62498a8edcba/Catalogue-Epic-Plan.md?plain=1#L80-L88

Влил версию девелопа, которую смерджил @Filosuf, в свою

2023-06-19 12:01 UTC, merged