add new Profile
BlackBullSquad/iOS-FakeNFT-StarterProject-Public pull request #88
Opened 2023-06-12 20:28 UTC by Filosuf

2023-06-12 20:46 UTC, Filosuf commented
С прошлой веткой возникли сложности которые я не смог разрешить, создал новую. Тестирование не обязательно как я понял. Хранение данных добавил - это запоминание сортировки на экране Мои NFT. Координатор, пообщавшись с командой, было решено не реализовывать

2023-06-13 07:32 UTC, maxim-papier reviewed
Кстати, заметил мелочь:
тут, в списке Избранных NFT должно быть не такое же расстояние между названием и рейтингом как в Мои NFT. Тут должно быть 4. См. макет: https://www.figma.
<img width="609" alt="Screenshot 2023-06-13 at 13 25 07" src="https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/assets/109724501/11050f96-3171-4dd7-9267-1f651107cab2">
com/file/k1LcgXHGTHIeiCv4XuPbND/FakeNFT-(YP)?type=design&node-id=641-19696&t=RgkvIt3vztYAwFCg-4

2023-06-13 07:44 UTC, maxim-papier approved these changes

2023-06-14 08:59 UTC, mmbabaev requested changes

2023-06-14 08:59 UTC, mmbabaev commented on FakeNFT/DesignSystem/ImageAsset.swift
> +        guard let image = UIImage(named: asset.rawValue) else { return .remove }
не очень хорошая практика возвращать рандомную картинку, если не нашли asset.rawValue. Тут будет лучше хотя бы assertionFailure вставить

2023-06-14 08:59 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewController.swift
> +            urlTextField.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -16)
это мелочь, но я обычно предпочитаю ставить leadingAnchor + centerX

2023-06-14 09:01 UTC, mmbabaev commented
[Евгений Теплухин - Ревью диплома.pdf](https://github.com/BlackBullSquad/iOS-FakeNFT-StarterProject-Public/files/11743816/-.pdf)

2023-06-14 09:21 UTC, Filosuf commented
Подскажите подробнее, что имеется ввиду под "продумать логику сохранения ссылки"? И вопрос по архитектуре, показалось что все экраны написаны одинаково. Спасибо.

2023-06-14 09:21 UTC, Filosuf commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewController.swift
> +            urlTextField.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -16)
Подскажите подробнее, что имеется ввиду под "продумать логику сохранения ссылки"? И вопрос по архитектуре, показалось что все экраны написаны одинаково. Спасибо.

2023-06-14 18:28 UTC, mmbabaev commented
Про хранение ссылки: предлагаю сделать так, чтобы пользователь не мог сохранить невалидную ссылку в текстовом поле. Для этого можно пробовать создавать `URL` из текста

2023-06-14 18:29 UTC, mmbabaev commented
Архитектура: экран catalogue сделан с viewModel, VC общается с сервисом через него

2023-06-14 18:32 UTC, Filosuf commented
Спасибо. Да ребята сделали через MVVM, я не успевал и сделал свои экраны проще

2023-06-17 20:42 UTC, mmbabaev approved these changes

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewController.swift
> +            if let url = NSURL(string: urlString) {
можно в один if через запятую

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewController.swift
> +                return UIApplication.shared.canOpenURL(url as URL)
вроде бы здесь ничего не мешает сразу создавать не NSURL, а URL

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewController.swift
> +                self?.viewModel.updateAvatar(url)
кажется здесь было бы лучше передавать в viewModel аргументом `alert.textFields?[0].text` и проверять if внутри нее

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewModel.swift
> +//    private(set) var profile: Profile? {
лучше убрать закомменченный код, работа выглядит неопрятно, в реальных проектах так не делают

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewModel.swift
> +
пустая функция

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewModel.swift
> +    func updateWebsite(_ newWebsite: URL) {
в swift обычно не пишут такие setter-методы, я бы просто открыл доступ к свойствам

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Edit Profile/EditProfileViewModel.swift
> +        let descript = descript ?? profile.description
лучше не делать такие длинные строки

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/FavoritesNFT/FavoritesNftViewController.swift
> +        updateView()
для меня выглядит странным, что одна функция просто делает вызов другой. Может тогда updateView и не нужна и можно поместить ее контент в initialization?

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/FavoritesNFT/FavoritesNftViewController.swift
> +            if let needShow = self?.viewModel.showErrorAlertState, needShow {
это мелочь, но в таких кейсах лучше использовать guard, так мы избегаем дополнительной вложенности

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/FavoritesNFT/FavoritesNftViewModel.swift
> +        getFavoritesNfts()
то же самое про прокси-функцию

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/FavoritesNFT/FavoritesNftViewModel.swift
> +    var showErrorAlertState: Bool { get }
не совсем понял идею почему нам нужно это булевское значение. Можно было бы сделать вместо него поменять название байндинга `showErrorAlertStateDidChange` на `showErrorAlert` и вызывать эту кложуру в случае ошибки сервиса

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/FavoritesNFT/FavoritesNftViewModel.swift
> +                self?.showErrorAlertState = true
здесь бы просто сказать View компоненту: `showErrorAlert()`

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/MyNFT/MyNftViewController.swift
> +            if let needShow = self?.viewModel.showErrorAlertState, needShow {
если убрать bool свойство состояния ошибки, то этот if будет не нужен

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/MyNFT/MyNftViewModel.swift
> +    //binding
можно тоже помечать как MARK

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/FavoritesNFT/FavoritesNftViewController.swift
> +            title: "Что-то пошло не так(",
повторяющийся код в алертах, можно вынести в общую функцию

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Profile/ProfileViewModel.swift
> +        var labelString = ""
можно не заводить переменную и сразу делать return. 
Если заводить переменную, то лучше ее делать let в таком случае

2023-06-17 20:42 UTC, mmbabaev commented on FakeNFT/Scenes/Profile/Profile/ProfileViewModel.swift
> +            labelString = ""
можно вставить assertionFailure, так как это неожидаемое поведение

2023-06-18 14:02 UTC, merged